const LOG_IN = "LOG_IN";
const LOG_OUT = "LOG_OUT";
const AUTHENTICATE = "AUTHENTICATE";
const USERNAME = "USERNAME";
const MOVIE = "MOVIE";
export { LOG_IN, LOG_OUT, AUTHENTICATE, USERNAME, MOVIE };
